# Generated by Django 4.2.5 on 2023-10-04 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidosExames',
            new_name='PedidoExame',
        ),
        migrations.RenameModel(
            old_name='TiposExames',
            new_name='TipoExame',
        ),
    ]
